# _config.yml

# required, replace with your own information -----
title: Helena's Website
author: Helena Schreder
description: > 
  TBD
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

